# Jekyll Configuration
theme: jekyll-theme-minimal
title: Surya Pratap Singh
description: Robotics MS at UMich
logo: assets/img/Pers_pic.png
google_analytics: G-placeholder
url_cv: assets/img/placeholder.jpg
url_github: https://github.com/silvery107
url_email: yulunz@umich.edu
url_linkedin: https://www.linkedin.com/in/yulun107
url_scholar: https://scholar.google.com/citations?user=mYGoL6IAAAAJ&hl=en
