# Jekyll Configuration
theme: jekyll-theme-minimal
title: Surya Pratap Singh
description: Robotics MS at UMich
logo: assets/img/Pers_pic.png
google_analytics: G-placeholder
url_cv: assets/img/placeholder.jpg
url_github: https://github.com/SuryaPratapSingh37
url_email: suryasin@umich.edu
url_linkedin: www.linkedin.com/in/surya-pratap-singh-736580174
url_scholar: https://scholar.google.com/citations?user=mYGoL6IAAAAJ&hl=en
